version: '3.7'
services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest  
    env_file: 
      - sqlvariables.env
    ports:
      - "1433:1433"
    expose: 
      - 1433
      
  config:
    build:
      dockerfile: DockerfileConfig
      context: .
      args: 
        TOOLS_PATH: "$PATH:/root/.dotnet/tools"
        MIGRATION_NAME: MigrationIdentity
        ACCEPT_EULA: Y
        IS_CONFIGURATION: TRUE
    ports:
      - "8081:81"  
    expose: 
    - 8080
    
  app:
    build:
      dockerfile: DockerfileBuildRun
      context: .
      args: 
        TOOLS_PATH: "$PATH:/root/.dotnet/tools"
        MIGRATION_NAME: Migration
        ACCEPT_EULA: Y
        IS_CONFIGURATION: TRUE
    ports:
      - "8080:80"  
    expose: 
    - 8080
    
